apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # "25%"
      maxUnavailable: 2 # "25%"
  replicas: 6
  selector:
    matchLabels:
      app: api
  template:
    metadata: 
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: api
          image: andremorita/k8s-api-product:latest
          ports:
            - containerPort: 8080
          env: 
            - name: MONGODB_URI
              value: mongodb://root:root@mongodbservice:27017/admin