apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata: 
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: api
          image: andremorita/kubernets-api:v2
          ports:
            - containerPort: 8080
          env: 
            - name: MONGODB_URI
              value: mongodb://root:root@mongodbservice:27017/admin